### ISSUE TITLE
Safe for concurrent minion access ?

### ISSUE THREAD

**Issue by minaguib** [clinta/salt-pwgen#4]
It appears that there's no serialization between reading the metadata file and rewriting it

Would it be safe to conclude there's a race condition if 2+ minions are having their pillars calculated by the master at the same time, both causing new passwords to be generated, that some metadata writes will be overwritten by others ?

**Comment by clinta** [comment]
I suppose this could be possible if you have multiple minions using the same password, identified by the same `pw_name`. The point of the module is to generate unique passwords for each minion though, which results in a unique metadata file for each one. So I don't think this is a practical concern.

Additionally the situation would correct itself the next time the pillar is updated, since at that time the metadata file will already exist and not be regenerated.

**Comment by minaguib** [comment]
Indeed. Sorry I misread. The contention would be around the metadata file per minion which is quite unlikely.
